server:
  port: 8081

spring:
    kafka:
        consumer:
          group-id: "astradb-connect-group"
    data:
      cassandra:
        keyspace-name: testkeyspace
        username: AixflMnklRMmdPdmjDfjcrkb
        password: ssf7yMb63nRwF0HSw9n1bzD.1QFEFNPc2Z0mPhnIZ7sCUvjgi++_PEjmhdrjfsDp9UOLs5E+yOzQZFA,r0aQQ8SWQvY8Xqf7Uc18lq.WEsxawsjET_GO1XCRSg_mY-e9
        schema-action: create_if_not_exists
        request:
          timeout: 15s
          throttler:
            max-concurrent-requests: 1000
            max-queue-size: 100000
        connection:
          connect-timeout: 15s
          init-query-timeout: 15s
topic:
  name: t.food.order

astra:
  api:
    application-token: AstraCS:AixflMnklRMmdPdmjDfjcrkb:354c677db41490f3e50a07b17f93e06f68fe939c8a8c761de77d2f99da2e1575
    database-id: 3047180d-25da-4045-b819-885c11beb5a9
    database-region: europe-west1
    cross-region-failback: true
    grpc:
      enabled: true
    metrics:
      export:
        enabled: true
        prometheus:
          enabled: true
      enabled: true

  # Connectivity to Cassandra
  cql:
    enabled: true
    download-scb:
      enabled: true
    driver-config:
      basic:
        session-keyspace: testkeyspace

management:
  server:
    port: 9091
    address: 127.0.0.1
  endpoints:
    web:
      exposure:
        include: "*"

datastax.astra:
  secure-connect-bundle: static/secure-connect-testdb.zip